- README.md
- src/main/java/io/tarantool/driver/proxy/ProxyOperationsMapping.java
- src/test/resources/cartridge/app/roles/api_router.lua
- src/test/resources/cartridge/app/roles/api_storage.lua
- src/test/resources/cartridge/init.lua
- src/test/resources/cartridge/testapp-scm-1.rockspec
- Get rid of proxy methods (fixed in https://github.com/tarantool/crud/pull/58) and bump CRUD version in tests
- Change the default method names in ProxyClient
> Update Proxy client for tarantool/crud version 0.3.0

- README.md
- src/main/java/io/tarantool/driver/metadata/ProxyTarantoolSpaceMetadataConverter.java
- src/main/java/io/tarantool/driver/proxy/ProxyOperationsMapping.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
- src/test/java/io/tarantool/driver/integration/SharedCartridgeContainer.java
- src/test/java/io/tarantool/driver/integration/TestProxyTarantoolClient.java
- src/test/resources/cartridge/app/roles/api_router.lua
- src/test/resources/cartridge/app/roles/api_storage.lua
- Use `cartridge.get_schema` by default
- Make README more useful
Fixes #27
> Use correct Cartridge metadata format compatible with ddl.get_schema()

- pom.xml
- src/main/java/io/tarantool/driver/api/TarantoolResultImpl.java
- src/main/java/io/tarantool/driver/core/AbstractTarantoolConnectionManager.java
- src/main/java/io/tarantool/driver/core/TarantoolConnection.java
- src/main/java/io/tarantool/driver/core/TarantoolConnectionImpl.java
- src/main/java/io/tarantool/driver/exceptions/TarantoolMetadataRequestException.java
- src/main/java/io/tarantool/driver/exceptions/TarantoolTupleConversionException.java
- src/main/java/io/tarantool/driver/metadata/ProxyTarantoolMetadata.java
- src/test/java/io/tarantool/driver/core/CustomConnection.java
- src/test/java/io/tarantool/driver/integration/ConnectionIT.java
- src/test/java/io/tarantool/driver/integration/SharedCartridgeContainer.java
- src/test/java/io/tarantool/driver/integration/StandaloneTarantoolClientIT.java
- src/test/resources/cartridge/.cartridge.yml
Fixes #57 
Includes changes:
- Make errors when retrieving metadata more readable
- Update driver to testcontainers 0.4.0 (possibly fixes #25)
- Add a message with server address the client established a connection to
> Handle correctly all errors when establishing connections

- src/main/java/io/tarantool/driver/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/ClusterTarantoolClient.java
- src/main/java/io/tarantool/driver/ClusterTarantoolTupleClient.java
- src/main/java/io/tarantool/driver/ConnectionSelectionStrategyFactory.java
- src/main/java/io/tarantool/driver/RequestRetryPolicy.java
- src/main/java/io/tarantool/driver/RequestRetryPolicyFactory.java
- src/main/java/io/tarantool/driver/RetryingTarantoolClient.java
- src/main/java/io/tarantool/driver/RetryingTarantoolTupleClient.java
- src/main/java/io/tarantool/driver/TarantoolClientConfig.java
- src/main/java/io/tarantool/driver/TarantoolRequestRetryPolicies.java
- src/main/java/io/tarantool/driver/api/cursor/OffsetCursor.java
- src/main/java/io/tarantool/driver/api/cursor/StartAfterCursor.java
- src/main/java/io/tarantool/driver/api/cursor/TarantoolCursorBase.java
- src/main/java/io/tarantool/driver/api/space/RetryingTarantoolSpaceOperations.java
- src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
- src/main/java/io/tarantool/driver/core/AbstractTarantoolConnectionManager.java
- src/main/java/io/tarantool/driver/core/TarantoolClusterConnectionManager.java
- src/main/java/io/tarantool/driver/mappers/DefaultSingleValueResultMapper.java
- src/test/java/io/tarantool/driver/RequestRetryPolicyTest.java
- src/test/java/io/tarantool/driver/integration/ClusterDiscoveryIT.java
- src/test/java/io/tarantool/driver/integration/ProxyCursorIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
- src/test/java/io/tarantool/driver/integration/RetryingTarantoolTupleClientIT.java
- src/test/resources/cartridge/app/roles/api_router.lua
These changes include:
- New RetryingTarantoolClient decorator which may be used for specific types of requests
- A framework for retry policies. The policy can use any stateful or stateless operations for determining if a request should be retried in case of an exception
- Breaking change: connection selection strategy moved to the TarantoolClientConfig.
Closes #53
> Add support for reconnection strategies

- README.md
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientMixedInstancesIT.java
- src/test/java/io/tarantool/driver/integration/SharedCartridgeContainerMixedInstances.java
- src/test/resources/cartridge/app/roles/api_router.lua
- src/test/resources/cartridge/app/roles/api_storage.lua
- src/test/resources/cartridge/topology_mixed.lua
Changes:
- changed ddl.get_schema function declarations in test resources
- made a set of integration tests that use tarantool with mixed topology (router with storage on same node)
- reflected changes in README.md
Fixes #72
Fixes #67
> New ddl.get_schema example in README.md

- src/main/java/io/tarantool/driver/exceptions/TarantoolAttemptsLimitException.java
- src/main/java/io/tarantool/driver/exceptions/TarantoolTimeoutException.java
- src/main/java/io/tarantool/driver/retry/RequestRetryPolicy.java
- src/main/java/io/tarantool/driver/retry/TarantoolRequestRetryPolicies.java
- src/test/java/io/tarantool/driver/integration/RetryingTarantoolTupleClientIT.java
- src/test/java/io/tarantool/driver/retry/RequestRetryPolicyTest.java
An error received from tarantool is wrapped either in `TarantoolTimeoutException` if timeout limit has been reached for retrying, or in `TarantoolAttemptsLimitException` if the retry limit has been reached.
Also tests on retrays were rewritten and supplemented.
Closes: #82
> Fix #82 - Last tarantool error with exception by retry

- .github/workflows/ubuntu-master.yml
- src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
- src/test/java/io/tarantool/driver/integration/TarantoolErrorsIT.java
- src/test/resources/cartridge/app/roles/api_router.lua
- Enable tests in CI for Tarantool versions 1.10 and 2.8
- Turn on docker layer caching for speeding up the tests and minimizing CI fails from the unavailable Tarantool installer, repositories, or source docker images
> Enable Tarantool CE versions matrix and Docker layers caching in CI

- src/main/java/io/tarantool/driver/auth/ChapSha1TarantoolAuthenticator.java
- src/main/java/io/tarantool/driver/auth/SimpleTarantoolCredentials.java
- src/main/java/io/tarantool/driver/auth/TarantoolAuthenticator.java
- src/main/java/io/tarantool/driver/exceptions/TarantoolBadCredentialsException.java
- src/main/java/io/tarantool/driver/handlers/TarantoolAuthenticationHandler.java
- src/test/java/io/tarantool/driver/integration/ConnectionIT.java
- src/test/resources/org/testcontainers/containers/server.lua
Now the connection to Tarantool under the guest user goes according
to the documentation rules: Username = "guest" or "", Password = "".
Previously, logging took place under guest, if you specify any name
without a password, for example:
Username = "notGuestName" or "", Password = ""
Closes #123
> Change the validation credentials of authorization

- pom.xml
It seems that next dependency org.testcontainers:junit-jupiter brings testcontainers transitively and there is no need for separate declaration (with separate version declaration)
> remove testcontainers core dependecy that comes transitively

- src/main/java/io/tarantool/driver/api/TarantoolVoidResult.java
- src/main/java/io/tarantool/driver/api/TarantoolVoidResultImpl.java
- src/main/java/io/tarantool/driver/api/space/ProxyTarantoolSpace.java
- src/main/java/io/tarantool/driver/api/space/RetryingTarantoolSpaceOperations.java
- src/main/java/io/tarantool/driver/api/space/TarantoolSpace.java
- src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
- src/main/java/io/tarantool/driver/proxy/InsertProxyOperation.java
- src/main/java/io/tarantool/driver/proxy/ProxyOperationsMappingConfig.java
- src/main/java/io/tarantool/driver/proxy/ReplaceProxyOperation.java
- src/main/java/io/tarantool/driver/proxy/TruncateProxyOperation.java
- src/main/java/io/tarantool/driver/proxy/UpsertProxyOperation.java
- src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
- src/test/java/io/tarantool/driver/integration/ProxyCursorIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientMixedInstancesIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTruncateIT.java
- src/test/java/io/tarantool/driver/integration/Utils.java
- src/test/java/io/tarantool/driver/proxy/ProxyOperationBuildersTest.java
Closes #93
The method calls crud.truncate of box.space.<space_obj>:truncate() for cluster and standalone client implementations.
I think that I should also add tests with truncate on different spaces and for a non-existent space.
Also I should return boolean not in array in TarantoolResultLmpl.java:58.
> Implement truncate() method

- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperation.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationAdd.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationBitwiseAnd.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationBitwiseOr.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationBitwiseXor.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationDelete.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationInsert.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationSet.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationSubtract.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperations.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleSpliceOperation.java
- src/main/java/io/tarantool/driver/api/tuple/operations/TupleUpdateOperation.java
- src/main/java/io/tarantool/driver/core/space/TarantoolSpace.java
- src/main/java/io/tarantool/driver/protocol/TarantoolRequest.java
- src/main/java/io/tarantool/driver/protocol/requests/TarantoolUpdateRequest.java
- src/main/java/io/tarantool/driver/protocol/requests/TarantoolUpsertRequest.java
- src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
This pr resolves two related problems:
1. We use update / upsert from TarantoolSpace, which updates the space via iproto. To specify the field to update, use fieldName. Previously, if we made a mistake in the name, no error occurred and a request was sent to tarantool where fieldIndex = -1, and this is correct for tarantool because it uses reverse index, so -1 is the last element in the Tuple. For now, we'll throw a TarantoolSpaceFieldNotFoundException if the specified fieldName doesn't exist.
2. The user creates operations by fieldName, which are subsequently used by the space.update/upsert functions. After using these functions, a field index field appears in operations that were missing. To remedy this situation, we make TupleOperation non-mutable. And every time we need to change the …
> Fix problems with TarantoolSpace.update/upsert

- pom.xml
- src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
- src/main/java/io/tarantool/driver/core/connection/ConnectionMode.java
Fixed concurrent access to the creation of a connection manager and its internal logic for establishing connections in the event of a partial or complete failure.
Fixes https://github.com/tarantool/cartridge-java/issues/149
> Fixed connection manager logic

- src/main/java/io/tarantool/driver/api/TarantoolClient.java
- src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/core/ProxyTarantoolClient.java
- src/main/java/io/tarantool/driver/core/RetryingTarantoolClient.java
- src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
- src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionManager.java
- src/test/java/io/tarantool/driver/integration/ClusterDiscoveryIT.java
- src/test/java/io/tarantool/driver/integration/ReconnectIT.java
- src/test/resources/cartridge/instances.yml
- src/test/resources/cartridge/topology.lua
Closes https://github.com/tarantool/cartridge-java/issues/115
Added a method to switch the connection mode to `PARTIAL` to start the process of establishing the lacking connections.
> Add method for reconnection

- README.md
- src/main/java/io/tarantool/driver/api/TarantoolClientConfigurator.java
- src/main/java/io/tarantool/driver/api/retry/RequestRetryPolicy.java
- src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
- src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/core/TarantoolClientConfiguratorImpl.java
- src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionFactory.java
- src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java
- src/main/java/io/tarantool/driver/exceptions/TarantoolNoSuchProcedureException.java
- src/main/java/io/tarantool/driver/exceptions/errors/BoxErrorKey.java
- src/main/java/io/tarantool/driver/exceptions/errors/ErrorCode.java
- src/main/java/io/tarantool/driver/exceptions/errors/ErrorKey.java
- src/main/java/io/tarantool/driver/exceptions/errors/ErrorMessageBuilder.java
- src/main/java/io/tarantool/driver/exceptions/errors/ErrorsErrorKey.java
- src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
- src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrorsParser.java
- src/main/java/io/tarantool/driver/handlers/TarantoolResponseHandler.java
- src/test/java/io/tarantool/driver/core/ProxyTarantoolClientBuilderTest.java
- src/test/java/io/tarantool/driver/core/RetryTarantoolClientBuilderTest.java
- src/test/java/io/tarantool/driver/integration/ClientFactoryIT.java
- src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientMixedInstancesIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTruncateIT.java
- src/test/java/io/tarantool/driver/integration/ReconnectIT.java
- src/test/java/io/tarantool/driver/integration/TarantoolErrorsIT.java
- src/test/resources/cartridge/app/roles/api_router.lua
Added refactoring for RequestRetryPolicies and classes in `exceptions.errors` package
Added new Exception called `TarantoolNoSuchProcedureException` for this message, so that the user can specify it in the retry policy
```
InnerErrorMessage:
code: 33
message: Procedure '*' is not defined
```
Closes https://github.com/tarantool/cartridge-java/issues/159
> Refactoring for RequestRetryPolicies and classes in exceptions.errors package

- src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
- src/main/java/io/tarantool/driver/api/TarantoolClientBuilder.java
- src/main/java/io/tarantool/driver/core/TarantoolClientBuilderImpl.java
- src/main/java/io/tarantool/driver/core/TarantoolClientConfiguratorImpl.java
- src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
- src/test/java/io/tarantool/driver/core/TarantoolClientBuilderTest.java
- src/test/java/io/tarantool/driver/integration/DoubleConversionIT.java
- src/test/java/io/tarantool/driver/integration/ProxyCursorIT.java
A new method has been added to simplify messagepack mapper configuration.
The user no longer needs to know about the default mapper and look for it. Now it is provided with a lambda with an interface for a simple mapper configuration. There is also a method for advanced users to allow them to pass their own mapper.
Also added method for specifying TarantoolClientConfig in TarantoolClient builder
> Added methods in client builder

- src/main/java/io/tarantool/driver/api/TarantoolClient.java
- src/main/java/io/tarantool/driver/api/TarantoolClusterAddressProvider.java
- src/main/java/io/tarantool/driver/cluster/AbstractDiscoveryClusterAddressProvider.java
- src/main/java/io/tarantool/driver/cluster/BinaryClusterDiscoveryEndpoint.java
- src/main/java/io/tarantool/driver/cluster/HTTPClusterDiscoveryEndpoint.java
- src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/core/ProxyTarantoolClient.java
- src/main/java/io/tarantool/driver/core/RetryingTarantoolClient.java
- src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
- src/main/java/io/tarantool/driver/core/connection/TarantoolClusterConnectionManager.java
- src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionManager.java
- src/test/java/io/tarantool/driver/cluster/TestWrappedClusterAddressProvider.java
- src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
- src/test/java/io/tarantool/driver/integration/ClusterDiscoveryIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientMixedInstancesIT.java
- src/test/java/io/tarantool/driver/integration/ReconnectIT.java
- src/test/resources/cartridge/app/roles/api_router.lua
- src/test/resources/cartridge/app/roles/api_storage.lua
Closes https://github.com/tarantool/cartridge-java/issues/163
> Added refresh callback to address provider

- src/main/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfig.java
- src/test/java/io/tarantool/driver/cluster/TarantoolClusterDiscoveryConfigTest.java
Throw exception if TarantoolClusterDiscoveryConfig.Builder().withEndpoint() called multiple times
Closes #173
> Prevent multiple call of TarantoolClusterDiscoveryConfig.Builder().withEndpoint()

- src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
- src/test/java/io/tarantool/driver/api/tuple/TarantoolNullFieldTest.java
Improve unit tests for TarantoolNullField class
Cleanup
Closes #150
> Improve unit tests for TarantoolNullField class

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
There are two aspects of this issue:
1) Incorrect fieldNumber in the index part metadata. All fieldNumber decreased by one for all indexes.
2) When the driver try to find suitable index by field name it compares fieldNumber in the indexPartMetadata and selected fields. This can lead to a situation where the driver will select the wrong index or will not be able to find the index at all.
Closes #203
> Set correct fieldNumber in indexMetadata

- CHANGELOG.md
- src/main/java/io/tarantool/driver/mappers/ConverterWrapper.java
- src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
- src/main/java/io/tarantool/driver/mappers/converters/Converter.java
- src/main/java/io/tarantool/driver/mappers/converters/ObjectConverter.java
- src/main/java/io/tarantool/driver/mappers/converters/ValueConverter.java
Now the connector doesn't search converter's targetType by reflection,
the targetType is stored with the converter. Operations to convert a value with targetType are faster.
You can see result of perfomance tests here:
[master](https://github.com/tarantool/cartridge-java/runs/6320224857?check_suite_focus=true#step:7:1496)
[fix/check_converter_by_target_type](https://github.com/tarantool/cartridge-java/runs/6387468617?check_suite_focus=true#step:7:1975)
Closes #212
> Fix checkConverterByTargetType logic

- pom.xml
I don't know why, but maven doesn't return head tag in these commits
https://github.com/tarantool/cartridge-java/commit/ce35c46086a7940ce3bad195165d4d872d385b74
https://github.com/tarantool/cartridge-java/commit/43c5c2c4aaf324e7a92d971269802f26e1fbe9c8
> Fix scm tag in pom.xml

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
- src/main/java/io/tarantool/driver/core/tuple/TarantoolTupleImpl.java
- src/test/java/io/tarantool/driver/api/tuple/TarantoolNullFieldTest.java
- src/test/java/io/tarantool/driver/api/tuple/operations/TupleOperationsTest.java
The `TarantoolNullField `class was not singleton and its only task it to provide functionality similar to `Optional.Empty()`.
Changes done to make `TarantoolNullField `behaves same as `Optional.Empty()`.
Closes #195
> Changes for TarantoolNullField class to singleton

- README.md
- src/main/java/io/tarantool/driver/api/metadata/TarantoolMetadataOperations.java
- src/test/java/io/tarantool/driver/integration/Utils.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertOptionsIT.java
> Add example how to calculate bucketId on client

- README.md
- src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
Change links to permalinks for proper document processing in GitHub Change links to local files to local links
> Fixes links in quickstart

- pom.xml
> Remove duplicate netty-transport dependency

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/core/space/ProxyTarantoolTupleSpace.java
- src/main/java/io/tarantool/driver/core/space/TarantoolTupleSpace.java
- src/main/java/io/tarantool/driver/mappers/TarantoolTupleResultMapperFactory.java
- src/main/java/io/tarantool/driver/mappers/TarantoolTupleResultMapperFactoryImpl.java
- src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
- src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactoryImpl.java
- src/test/java/io/tarantool/driver/benchmark/TarantoolSetup.java
- src/test/java/io/tarantool/driver/core/proxy/ProxyOperationBuildersTest.java
- src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
- src/test/java/io/tarantool/driver/mappers/TarantoolCallResultMapperTest.java
- src/test/java/io/tarantool/driver/mappers/TarantoolResultMapperTest.java
We need it to create universal mapper that can parse crud and box responses.
Also with this factory we can't see inherited methods.
Closes #321
> Add TarantoolTupleResultMapper factory

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/SingleValueCallResultImpl.java
- src/test/java/io/tarantool/driver/mappers/TarantoolCallResultMapperTest.java
I decided to not make a separate `SingleValueCallResult` parser for batch operations specifically because I believe that the return format must be fixed in tarantool/crud and it will change in the future. So I added a new case to the common parser and refactored it a bit.
Fixes #334
> Batch operation errors parsing

- src/main/java/io/tarantool/driver/mappers/TarantoolTupleResultMapperFactory.java
> Fix javadoc warnings in TarantoolTupleResultMapper

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/TarantoolClientConfigurator.java
- src/main/java/io/tarantool/driver/core/TarantoolClientConfiguratorImpl.java
- src/test/java/io/tarantool/driver/core/RetryTarantoolClientBuilderTest.java
We could create retrying client with executor only via `new RetryingClient`, now we can use builder for this purpose 
Closes #339
> Add retrying executor option in client builder

- docs/RetryingTarantoolClient.md
- src/test/java/io/tarantool/driver/TarantoolUtils.java
- src/test/java/io/tarantool/driver/integration/ReconnectIT.java
- src/test/resources/cartridge/app/roles/api_router.lua
Update retrying client documentation
Closes #309
> Update retrying client documentation

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/TarantoolResultFactory.java
- src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
- src/main/java/io/tarantool/driver/core/TarantoolTupleResultImpl.java
- src/main/java/io/tarantool/driver/core/metadata/RowsMetadataToTarantoolTupleResultConverter.java
- src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolResultConverter.java
- src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolTupleResultConverter.java
For `TarantoolResultImpl`, `TarantoolTupleResultImpl`
Changing the access to protected because of its internal functionality. They are used in converters.
Closes #326
> Access Changed from public to protected for TarantoolResultImpl and TarantoolTupleResultImpl #326

- CHANGELOG.md
- src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
- src/test/java/io/tarantool/driver/mappers/DefaultMessagePackMapperTest.java
> Add deep copy instead of shallow copy in mappers

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/metadata/RowsMetadataToTarantoolTupleResultConverter.java
- src/main/java/io/tarantool/driver/mappers/AbstractResultMapper.java
- src/main/java/io/tarantool/driver/mappers/factories/ArrayValueToTarantoolTupleResultMapperFactory.java
- src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactory.java
- src/main/java/io/tarantool/driver/mappers/factories/ResultMapperFactoryFactoryImpl.java
- src/main/java/io/tarantool/driver/mappers/factories/RowsMetadataToTarantoolTupleResultMapperFactory.java
- src/main/java/io/tarantool/driver/mappers/factories/SingleValueResultMapperFactory.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
- src/test/resources/cartridge/app/roles/api_router.lua
To use mappers for custom behavior
```java
MessagePackMapper valueMapper = client.getConfig().getMessagePackMapper();
ResultMapperFactoryFactory factory =
client.getResultMapperFactoryFactory();
CallResultMapper callReturnMapper = factory.createMapper()
.withSingleValueConverter(
factory.createMapper()
.withArrayValueToTarantoolTupleResultConverter(valueMapper, null)
.withRowsMetadataToTarantoolTupleResultMapper(valueMapper, null)
.buildMessagePackMapper(valueMapper.copy())
)
.buildCallResultMapper(valueMapper.copy());
Object crudResult =
client.call("crud.select", Collections.singletonList("test_space"), returnMapper).join();
assertTrue(crudResult instanceof TarantoolTupleResultImpl);
Object boxResult =
client.call("select_request_counters", new ArrayList<>(), returnMapper).join(); …
```
> Add ability to use different converters via factory

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/retry/RequestRetryPolicy.java
- src/main/java/io/tarantool/driver/api/retry/RequestTimeoutOperation.java
- src/main/java/io/tarantool/driver/api/retry/RetryingAsyncOperation.java
- src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
> Split retrying into more detailed modules

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/space/ProxyTarantoolSpace.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceDeleteOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertManyOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceReplaceManyOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceReplaceOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceUpdateOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceUpsertOptionsIT.java
@ akudiyar changed the behaviour https://github.com/tarantool/cartridge-java/commit/57af227042cdc6402749e39a70a49ae61b94eb9a#diff-b2ae385ada02a75ad946141c7af41540970760d41d02d54209c00eabdc9bc8e3L175
I suggest make "OR" condition. If we have options.timeout, we use it, otherwise we use client.getTimeout()
> Add default client request timeout

- CHANGELOG.md
- src/main/java/io/tarantool/driver/mappers/converters/value/ArrayValueToTarantoolTupleResultConverter.java
- src/test/java/io/tarantool/driver/mappers/TarantoolCallResultMapperTest.java
It's needed when we want to take maps in the array. Springdata can map map structures. Using AUTO converter we can't map a simple array without tuples to the array and pass conversion control to the next layer.
Needed for https://github.com/tarantool/cartridge-springdata/issues/123
> Add can convert value to TupleResultConverter

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
- src/main/java/io/tarantool/driver/core/tuple/TarantoolTupleImpl.java
- src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
It's needed when we expected crud and box responses by one mapper(AUTO mapper in cartridge-springdata). In case when we obtain box response and we didn't have prepared metadata from ddl/_vspace, we can't map these values to Entity without metadata and we can't check whether we have it or not. And we can't raise an exception that we don't have metadata before because we can take it from crud response. Springdata doesn't see a difference between crud and box responses, it only got TarantoolTupleResult
Needed for https://github.com/tarantool/cartridge-springdata/issues/123
> Add metadataFormatIsEmpty in TarantoolTuple

- .github/workflows/tests-ce.yml
- CHANGELOG.md
- pom.xml
- src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
- src/main/java/io/tarantool/driver/core/tuple/TarantoolTupleImpl.java
- src/main/java/io/tarantool/driver/mappers/converters/object/DefaultInstantToExtensionValueConverter.java
- src/main/java/io/tarantool/driver/mappers/converters/value/defaults/DefaultExtensionValueToInstantConverter.java
- src/main/java/io/tarantool/driver/mappers/factories/DefaultMessagePackMapperFactory.java
- src/test/java/io/tarantool/driver/TarantoolUtils.java
- src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
- src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
- src/test/java/io/tarantool/driver/integration/ConnectionIT.java
- src/test/java/io/tarantool/driver/integration/ConvertersWithClusterClientIT.java
- src/test/java/io/tarantool/driver/integration/ConvertersWithProxyClientIT.java
- src/test/java/io/tarantool/driver/integration/OffsetCursorIT.java
- src/test/java/io/tarantool/driver/integration/SharedTarantoolContainer.java
- src/test/java/io/tarantool/driver/mappers/DefaultInstantConverterTest.java
- src/test/resources/cartridge/app/roles/api_storage.lua
- src/test/resources/org/testcontainers/containers/server.lua
This converter can support parsing Datetime tarantool type to java Instant. Because Instant doesn't support timezone and offset we can't support full DateTime type features. 
Also to test new features we need to have variants of tarantool in CI so we did:
- Changing tarantool container init to use version depending on CI TARANTOOL_VERSION variable. 
- Updating cartridge-java-testcontainer so that the cartridge container is based on the same image as tarantool container (see https://github.com/tarantool/cartridge-java-testcontainers/commit/12927b943b84e5cea1a9b1995c4917b159b7c76c).
But we have one problem with versions. Tarantool on Docker hub has fixed patches only for 2.10 version if we speak about centos versions. Besides 2.10 versions we only can use 1.x, 2.x tags. That means the …
> Add Datetime to Instant converter

- CHANGELOG.md
- README.md
- src/main/java/io/tarantool/driver/core/tuple/TarantoolTupleImpl.java
- src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
It was broken after renaming here https://github.com/tarantool/cartridge-java/pull/372/commits/b0d5358922421a4026caee89d3f6ea64914ea450#r1149084554
> Fix hasMetadata logic

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionFactory.java
- src/test/java/io/tarantool/driver/integration/ConnectionIT.java
- src/test/java/io/tarantool/driver/integration/SharedTarantoolContainer.java
> Fix lack of closing when greeting fails

- CHANGELOG.md
- src/main/java/io/tarantool/driver/core/RetryingTarantoolClient.java
- src/test/java/io/tarantool/driver/benchmark/BenchmarkRunner.java
- src/test/java/io/tarantool/driver/benchmark/TarantoolSetup.java
Before changing:
```jmh
Benchmark                   Mode  Cnt      Score       Error  Units
BenchmarkRunner.spaceCall  thrpt    5  74844.508 ± 16460.492  ops/s
```
After changing:
```jmh
Benchmark                   Mode  Cnt       Score        Error  Units
BenchmarkRunner.spaceCall  thrpt    5  275476.264 ± 256775.771  ops/s
```
* Error means mean margin between iteration:
> This is the margin of error for the score. In most cases, that is a half of [confidence interval](http://en.wikipedia.org/wiki/Confidence_interval). Think about it as if there is a "±" sign between "Score" and "Score error". In fact, the human-readable log will show that:
```
Iteration   1: 334564.445 ops/s
Iteration   2: 226016.924 ops/s
Iteration   3: 343260.667 ops/s
Iteration   4: 190627.608 ops/s
Iteration   5: …
```
> Get rid of double executor in retrying

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/metadata/TarantoolIndexPartMetadata.java
- src/main/java/io/tarantool/driver/core/metadata/DDLTarantoolSpaceMetadataConverter.java
- src/main/java/io/tarantool/driver/core/metadata/TarantoolIndexMetadataConverter.java
- src/main/java/io/tarantool/driver/core/metadata/TarantoolIndexPartMetadataImpl.java
- src/test/java/io/tarantool/driver/api/conditions/ConditionsTest.java
- src/test/java/io/tarantool/driver/core/metadata/TestMetadataContainer.java
- src/test/resources/cartridge/app/roles/api_storage.lua
Change TarantoolIndexPartMetadata.path type from String to Object to store String or int values
Closes #395
> Add support of numerical index path

- src/main/java/io/tarantool/driver/core/TarantoolResultImpl.java
- src/main/java/io/tarantool/driver/core/metadata/TarantoolFieldMetadataImpl.java
- src/main/java/io/tarantool/driver/core/tuple/TarantoolFieldImpl.java
- src/main/java/io/tarantool/driver/core/tuple/TarantoolTupleImpl.java
<details><summary>before</summary>
<p>
```
io.tarantool.driver.core.TarantoolTupleResultImpl@6a1530b5
```
</p>
</details> 
<details><summary>after</summary>
<p>
```
TarantoolResultImpl{tuples=[TarantoolTupleImpl{
spaceMetadata=TarantoolSpaceMetadata{spaceId=0, ownerId=0, spaceName='null', spaceFormatMetadata={profile_id=TarantoolFieldMetadataImpl{fieldName='profile_id', fieldType='unsigned', fieldPosition=0, isNullable=false}, bucket_id=TarantoolFieldMetadataImpl{fieldName='bucket_id', fieldType='unsigned', fieldPosition=1, isNullable=false}, fio=TarantoolFieldMetadataImpl{fieldName='fio', fieldType='string', fieldPosition=2, isNullable=false}, age=TarantoolFieldMetadataImpl{fieldName='age', fieldType='unsigned', fieldPosition=3, isNullable=false}, …
```
> Add toString in tarantool proxy entities

- src/test/java/io/tarantool/driver/TarantoolUtils.java
- src/test/java/io/tarantool/driver/integration/ConnectionIT.java
- src/test/java/io/tarantool/driver/integration/ConvertersWithClusterClientIT.java
- src/test/java/io/tarantool/driver/integration/ConvertersWithProxyClientIT.java
- src/test/java/io/tarantool/driver/integration/ReconnectIT.java
- src/test/java/io/tarantool/driver/integration/Utils.java
- src/test/java/io/tarantool/driver/integration/ssl/SslClientITEnterprise.java
- src/test/java/io/tarantool/driver/integration/ssl/SslClientMTlsITEnterprise.java
> Remove incorrect imports of transitive dependencies

- CHANGELOG.md
- src/main/java/io/tarantool/driver/mappers/converters/object/DefaultInstantToExtensionValueConverter.java
- src/main/java/io/tarantool/driver/mappers/converters/value/defaults/DefaultExtensionValueToInstantConverter.java
- src/test/java/io/tarantool/driver/integration/ConvertersWithClusterClientIT.java
- src/test/java/io/tarantool/driver/mappers/DefaultInstantConverterTest.java
ref: https://www.tarantool.io/en/doc/latest/dev_guide/internals/msgpack_extensions/#the-datetime-type
Closes #408
> Fix Instant converter to parse 8 bytes datetime

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
- src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/Mode.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/package-info.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDSelectOptions.java
- src/main/java/io/tarantool/driver/core/proxy/SelectProxyOperation.java
- src/test/java/io/tarantool/driver/core/proxy/ProxyOperationBuildersTest.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
> Added "mode" option for crud select operation

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/space/options/InsertManyOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithRollbackOnErrorOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithStopOnErrorOptions.java
- src/main/java/io/tarantool/driver/api/space/options/ReplaceManyOptions.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/Mode.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/RollbackOnError.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/StopOnError.java
- src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyInsertManyOptions.java
- src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyReplaceManyOptions.java
- src/main/java/io/tarantool/driver/core/space/ProxyTarantoolSpace.java
- src/test/java/io/tarantool/driver/core/proxy/ProxyOperationBuildersTest.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertManyOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceReplaceManyOptionsIT.java
> Use enum for proxy client parameters

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/space/options/BaseOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithBucketIdOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithFieldsOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithModeOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithRollbackOnErrorOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithStopOnErrorOptions.java
- src/main/java/io/tarantool/driver/api/space/options/OperationWithTimeoutOptions.java
- src/main/java/io/tarantool/driver/api/space/options/Options.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/Mode.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/ProxyOption.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/RollbackOnError.java
- src/main/java/io/tarantool/driver/api/space/options/enums/crud/StopOnError.java
- src/main/java/io/tarantool/driver/api/space/options/proxy/ProxySelectOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDAbstractOperationOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDBaseOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDBatchOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDBucketIdOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDDeleteOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDInsertOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDReplaceOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDReturnOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDSelectOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDUpdateOptions.java
- src/main/java/io/tarantool/driver/core/proxy/CRUDUpsertOptions.java
- src/test/java/io/tarantool/driver/core/proxy/CRUDOperationOptionsTest.java
- src/test/java/io/tarantool/driver/core/proxy/ProxyOperationBuildersTest.java
> Use enum for inner API to determine proxy options

- pom.xml
- src/test/java/io/tarantool/driver/integration/CartridgeMixedInstancesContainer.java
- src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
- src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
- src/test/java/io/tarantool/driver/integration/ReconnectIT.java
- src/test/java/io/tarantool/driver/integration/SharedCartridgeContainer.java
- src/test/resources/logback-test.xml
Re-building images between test suites is unnecessary, and this can be mitigated by using image names.
This patch does the following:
- Improves reusing Docker images by assigning image names and using layers in the Dockerfile
- Improves logging for docker-java client
> Improve reusing Docker images between tests

- .gitignore
- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
- src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
- src/main/java/io/tarantool/driver/api/TarantoolEvalOperations.java
- src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/core/ProxyTarantoolClient.java
- src/main/java/io/tarantool/driver/core/RetryingTarantoolClient.java
- src/main/java/io/tarantool/driver/core/proxy/AbstractProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/InsertManyProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/InsertProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/ReplaceManyProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/ReplaceProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/SelectProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/TruncateProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/UpdateProxyOperation.java
- src/main/java/io/tarantool/driver/core/proxy/UpsertProxyOperation.java
- src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
- src/main/java/io/tarantool/driver/mappers/converters/object/DefaultCollectionToArrayValueConverter.java
- src/main/java/io/tarantool/driver/mappers/converters/value/defaults/DefaultArrayValueToListConverter.java
- src/main/java/io/tarantool/driver/mappers/factories/DefaultMessagePackMapperFactory.java
- src/main/java/io/tarantool/driver/protocol/requests/TarantoolCallRequest.java
- src/main/java/io/tarantool/driver/protocol/requests/TarantoolEvalRequest.java
- src/test/java/io/tarantool/driver/core/proxy/ProxyOperationBuildersTest.java
- src/test/java/io/tarantool/driver/mappers/DefaultMessagePackMapperTest.java
Also make some performance improvements by removing unnecessary wrapper object creation.
See individual commit messages for details about the changes.
Closes #432
> Use Collection instead of List as arguments type in TarantoolClient

- pom.xml
- src/test/java/io/tarantool/driver/TarantoolUtils.java
- src/test/java/io/tarantool/driver/TarantoolUtilsTest.java
The actual version will assume that version "3.2" is less than version "2.3" because `3 >= 2 && 2 >= 3` will computed as false.
(seems that internal changes do not need to be reflected in Changelog)
Related issues: none
> Fix checking the current Tarantool version for minimum requirements

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/connection/TarantoolConnectionSelectionStrategies.java
> WIP - Fix infinite loop when retrying to get a connection

- src/main/java/io/tarantool/driver/cluster/BinaryDiscoveryClusterAddressProvider.java
- src/test/java/io/tarantool/driver/integration/ClusterDiscoveryIT.java
Fix connection to multiple instances doesn't shut down EventLoopGroup by finishing the work
Closes #435
> Add connection close

- pom.xml
- src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
- src/main/java/io/tarantool/driver/codecs/MessagePackFrameDecoder.java
- src/main/java/io/tarantool/driver/codecs/MessagePackFrameEncoder.java
- src/main/java/io/tarantool/driver/core/TarantoolChannelInitializer.java
- src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
- src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionFactory.java
- src/main/java/io/tarantool/driver/handlers/TarantoolRequestHandler.java
Previously we were creating a new buffer and MsgPack packer on each request. This resulted in dramatic overload of GC with short-lived byte arrays. The new approach tries to maximize reusing of these byte arrays.
> Optimize usage of the Netty's and MsgPack's buffers

- src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
- src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
- src/main/java/io/tarantool/driver/core/TarantoolRequestMetadata.java
- src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionImpl.java
- src/main/java/io/tarantool/driver/core/space/TarantoolSpace.java
- src/main/java/io/tarantool/driver/mappers/AbstractResultMapper.java
- src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
- src/main/java/io/tarantool/driver/mappers/MessagePackObjectMapper.java
- src/main/java/io/tarantool/driver/mappers/MessagePackValueMapper.java
- src/main/java/io/tarantool/driver/mappers/converters/object/DefaultMapToMapValueConverter.java
- src/main/java/io/tarantool/driver/mappers/converters/value/defaults/DefaultMapValueToMapConverter.java
- src/main/java/io/tarantool/driver/protocol/TarantoolHeader.java
- src/main/java/io/tarantool/driver/protocol/TarantoolRequestSignature.java
- src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
- src/test/java/io/tarantool/driver/protocol/TarantoolRequestSignatureTest.java
`toValue` and `fromValue` methods in DefaultMessagePackMapper are hot spots as they are called on each request. This code was first written using Java streams, but while it allowed to make the code more readable, the streams are not very well-suitable for this task. The Java streams work better when we can execute the chained lambda functions in parallel on an executor, but are worse when replacing the normal `for` loops - they add significant overhead because of a lot of created auxiliary classes and objects in runtime.
Now as the DefaultMessagePackMapper code is stable we can replace the stream-based code with more optimized loop-based code.
> Replace streams with loops in DefaultMessagePackMapper

- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
> Add example for AFTER crud operations option

- src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
- src/main/java/io/tarantool/driver/api/space/options/crud/OperationWithYieldEveryOptions.java
- src/main/java/io/tarantool/driver/api/space/options/crud/enums/ProxyOption.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
> Add support for "yield_every" option

- CHANGELOG.md
- profile.jfc
- src/test/java/io/tarantool/driver/benchmark/ClusterBenchmarkRunner.java
- src/test/java/io/tarantool/driver/benchmark/ClusterTarantoolSetup.java
- src/test/resources/cartridge/app/roles/api_router.lua
- src/test/resources/org/testcontainers/containers/cluster_benchmark.lua
Benchmark results on commit https://github.com/tarantool/cartridge-java/commit/a6199e8268577517167492191b0c5989fbcf99e8 (before optimizations):
```
Total time: 00:33:33
Benchmark                                            Mode  Cnt      Score      Error  Units
ClusterBenchmarkRunner.readDataUsingCallAPI         thrpt   10  13761.025 ± 2657.463  ops/s
ClusterBenchmarkRunner.readDataUsingCallAPI:·jfr    thrpt             NaN               ---
ClusterBenchmarkRunner.readDataUsingSpaceAPI        thrpt   10  12033.690 ± 2032.909  ops/s
ClusterBenchmarkRunner.readDataUsingSpaceAPI:·jfr   thrpt             NaN               ---
ClusterBenchmarkRunner.writeDataUsingCallAPI        thrpt   10   6175.897 ±  630.966  ops/s
ClusterBenchmarkRunner.writeDataUsingCallAPI:·jfr   thrpt             NaN …
```
> Add benchmark for cluster API

- src/main/java/io/tarantool/driver/api/space/options/DeleteOptions.java
- src/main/java/io/tarantool/driver/api/space/options/InsertManyOptions.java
- src/main/java/io/tarantool/driver/api/space/options/InsertOptions.java
- src/main/java/io/tarantool/driver/api/space/options/ReplaceManyOptions.java
- src/main/java/io/tarantool/driver/api/space/options/ReplaceOptions.java
- src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
- src/main/java/io/tarantool/driver/api/space/options/UpdateOptions.java
- src/main/java/io/tarantool/driver/api/space/options/UpsertOptions.java
- src/main/java/io/tarantool/driver/api/space/options/crud/OperationWithVshardRouterOptions.java
- src/main/java/io/tarantool/driver/api/space/options/crud/enums/ProxyOption.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceDeleteOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertManyOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceReplaceManyOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceReplaceOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceUpdateOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceUpsertOptionsIT.java
> Add support for "vshard_router" option

- CHANGELOG.md
- src/main/java/io/tarantool/driver/api/space/options/DeleteOptions.java
- src/main/java/io/tarantool/driver/api/space/options/InsertManyOptions.java
- src/main/java/io/tarantool/driver/api/space/options/InsertOptions.java
- src/main/java/io/tarantool/driver/api/space/options/ReplaceManyOptions.java
- src/main/java/io/tarantool/driver/api/space/options/ReplaceOptions.java
- src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
- src/main/java/io/tarantool/driver/api/space/options/UpdateOptions.java
- src/main/java/io/tarantool/driver/api/space/options/UpsertOptions.java
- src/main/java/io/tarantool/driver/api/space/options/crud/OperationWithFetchLatestMetadataOptions.java
- src/main/java/io/tarantool/driver/api/space/options/crud/enums/ProxyOption.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceDeleteOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertManyOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceInsertOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceReplaceManyOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceReplaceOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceUpdateOptionsIT.java
- src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceUpsertOptionsIT.java
> Add support for "fetch_latest_metadata" option
