src/main/java/io/tarantool/driver/api/tuple/TarantoolFieldImpl.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolTupleImpl.java
src/test/java/io/tarantool/driver/api/tuple/TarantoolTupleTest.java

Add TarantoolTuple setField by position method
https://www.notion.so/TarantoolTuple-0530683ae98a41cf9f3f6574c31ba056

Add TarantoolTuple setField by position method

---

.github/workflows/maven.yml

- Setup Java build
- Run verify (checkstyle + units) on each pull/master commit

Add Github CI

---

src/main/java/io/tarantool/driver/TarantoolClientConfig.java
src/main/java/io/tarantool/driver/api/space/TarantoolSpace.java
src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolTupleImpl.java
src/main/java/io/tarantool/driver/mappers/DefaultArrayValueToTarantoolTupleConverter.java
src/main/java/io/tarantool/driver/mappers/DefaultFloatConverter.java
src/main/java/io/tarantool/driver/mappers/DefaultListValueConverter.java
src/main/java/io/tarantool/driver/mappers/DefaultMapValueConverter.java
src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java
src/main/java/io/tarantool/driver/mappers/DefaultTarantoolTupleValueConverter.java
src/main/java/io/tarantool/driver/mappers/TarantoolResultMapperFactory.java
src/main/java/io/tarantool/driver/metadata/TarantoolMetadata.java
src/main/java/io/tarantool/driver/protocol/TarantoolRequestFieldType.java
src/main/java/io/tarantool/driver/protocol/TarantoolRequestType.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolDeleteRequest.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolInsertRequest.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolReplaceRequest.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolSelectRequest.java
src/test/java/io/tarantool/driver/integration/StandaloneTarantoolClientIT.java
src/test/resources/org/testcontainers/containers/server.lua

https://www.notion.so/CRUD-094381826d32481a8b604ea45ad5cfb5

Add base implementation СRUD operations delete, insert, replace

---

src/main/java/io/tarantool/driver/TarantoolConnection.java
src/main/java/io/tarantool/driver/TarantoolConnectionImpl.java
src/main/java/io/tarantool/driver/mappers/TarantoolResultMapperFactory.java
src/main/java/io/tarantool/driver/protocol/TarantoolRequestFieldType.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolCallRequest.java
src/test/java/io/tarantool/driver/integration/StandaloneTarantoolClientIT.java
src/test/resources/org/testcontainers/containers/server.lua

https://www.notion.so/call-f36f9dde34af4946bab1ea32438ff735

Implement call request

---

src/main/java/io/tarantool/driver/TarantoolConnection.java
src/main/java/io/tarantool/driver/TarantoolConnectionImpl.java
src/main/java/io/tarantool/driver/protocol/TarantoolRequestFieldType.java
src/main/java/io/tarantool/driver/protocol/TarantoolRequestType.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolEvalRequest.java
src/test/java/io/tarantool/driver/integration/StandaloneTarantoolClientIT.java

https://www.notion.so/eval-2116a4e89ca14b3eabb45eb724263239

Implement eval request

---

pom.xml

Add sourceEncoding property value

---

src/main/java/io/tarantool/driver/api/space/ProxyTarantoolSpace.java
src/main/java/io/tarantool/driver/api/space/TarantoolSpace.java
src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
src/main/java/io/tarantool/driver/api/tuple/operations/TarantoolUpdateOperationType.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperation.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationAdd.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationBitwiseAnd.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationBitwiseOr.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationBitwiseXor.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationDelete.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationInsert.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationSet.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationSubtract.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperations.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleSpliceOperation.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleUpdateOperation.java
src/main/java/io/tarantool/driver/api/tuple/operations/package-info.java
src/main/java/io/tarantool/driver/protocol/operations/TupleOperations.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolUpdateRequest.java
src/main/java/io/tarantool/driver/protocol/requests/TarantoolUpsertRequest.java
src/main/java/io/tarantool/driver/proxy/UpdateProxyOperation.java
src/main/java/io/tarantool/driver/proxy/UpsertProxyOperation.java
src/test/java/io/tarantool/driver/api/tuple/operations/TupleOperationsTest.java
src/test/java/io/tarantool/driver/api/tuple/operations/TupleUpdateOperationTest.java
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
src/test/java/io/tarantool/driver/integration/StandaloneTarantoolClientIT.java
src/test/java/io/tarantool/driver/protocol/TupleOperationsTest.java
src/test/java/io/tarantool/driver/proxy/ProxyOperationBuildersTest.java

Add update() method taking TarantoolTuple

---

src/main/java/io/tarantool/driver/metadata/ProxyTarantoolSpaceMetadataConverter.java
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java

fieldType value in space metadata

---

src/main/java/io/tarantool/driver/api/TarantoolClient.java
src/main/java/io/tarantool/driver/api/conditions/Conditions.java
src/main/java/io/tarantool/driver/api/space/ProxyTarantoolSpace.java
src/main/java/io/tarantool/driver/api/space/TarantoolSpace.java
src/main/java/io/tarantool/driver/api/space/TarantoolSpaceOperations.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolFieldImpl.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolTupleImpl.java
src/main/java/io/tarantool/driver/core/TarantoolConnectionSelectionStrategies.java
src/main/java/io/tarantool/driver/metadata/TarantoolSpaceMetadata.java
src/test/java/io/tarantool/driver/core/CustomConnection.java
src/test/java/io/tarantool/driver/core/ParallelRoundRobinStrategyTest.java
src/test/java/io/tarantool/driver/core/RoundRobinStrategyTest.java

Simplify code in connection selection strategies

---

.github/workflows/ubuntu-master.yml
pom.xml
src/main/java/io/tarantool/driver/AbstractTarantoolClient.java
src/main/java/io/tarantool/driver/ProxyTarantoolClient.java
src/main/java/io/tarantool/driver/api/TarantoolCallOperations.java
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
src/test/resources/cartridge/app/roles/api_router.lua

Update tarantool-java-testcontainers to 0.2.3

---

src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
src/main/java/io/tarantool/driver/mappers/DefaultNilConverter.java
src/test/java/io/tarantool/driver/mappers/DefaultMessagePackMapperTest.java

WIP: NPE in toValue with null input

---

src/main/java/io/tarantool/driver/mappers/DefaultIntegerValueToDoubleConverter.java
src/main/java/io/tarantool/driver/mappers/DefaultIntegerValueToFloatConverter.java
src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java
src/test/java/io/tarantool/driver/mappers/CustomMappersTest.java
src/test/java/io/tarantool/driver/mappers/DefaultMessagePackMapperTest.java

Custom object converter is not applied on complex types #42
Add default Long-to-Double, Integer-to-Float converters #61

Fix two bugs in converters

---

src/main/java/io/tarantool/driver/mappers/DefaultMapValueConverter.java
src/test/java/io/tarantool/driver/mappers/DefaultMessagePackMapperTest.java

Filter out nil values in default map value converter

---

pom.xml
src/main/java/io/tarantool/driver/mappers/DefaultBigDecimalConverter.java
src/test/java/io/tarantool/driver/mappers/DefaultBigDecimalConverterTest.java

Correctly encode fixed point decimals

---

src/main/java/io/tarantool/driver/AbstractTarantoolClient.java
src/main/java/io/tarantool/driver/core/TarantoolConnectionImpl.java
src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
src/test/java/io/tarantool/driver/integration/ConnectionIT.java
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java
src/test/resources/cartridge/app/roles/api_router.lua
src/test/resources/cartridge/app/roles/api_storage.lua

* Fix logic for determinism for asynchronous tests
* Always failing tests have been fixed
A detailed description can be found in the commit message

Fix flaky tests

---

README.md
docs/test-convention.md

Closes https://github.com/tarantool/cartridge-springdata/issues/47

Add tests convention

---

src/main/java/io/tarantool/driver/api/tuple/TarantoolTuple.java
src/main/java/io/tarantool/driver/api/tuple/TarantoolTupleImpl.java
src/main/java/io/tarantool/driver/mappers/DefaultCharacterConverter.java
src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java
src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
src/test/java/io/tarantool/driver/mappers/DefaultCharacterConverterTest.java

Added default converter form StringValue of single symbol to Character type.
Closes #64

Add default converter for Character type

---

src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationBitwiseXor.java
src/main/java/io/tarantool/driver/api/tuple/operations/TupleOperationDelete.java
src/test/java/io/tarantool/driver/api/tuple/operations/TupleOperationsTest.java

Fix typo in TarantoolOperations

---

src/main/java/io/tarantool/driver/exceptions/TarantoolAccessDeniedException.java
src/main/java/io/tarantool/driver/exceptions/errors/ErrorCode.java
src/main/java/io/tarantool/driver/exceptions/errors/TarantoolErrors.java
src/test/java/io/tarantool/driver/integration/TarantoolErrorsIT.java
src/test/resources/cartridge/app/roles/api_router.lua

Needed for [1].
1. https://github.com/tarantool/cartridge-springdata/issues/95

Add access denied exception

---

src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
src/test/java/io/tarantool/driver/integration/ReconnectIT.java
src/test/java/io/tarantool/driver/integration/SharedCartridgeContainer.java

Closes https://github.com/tarantool/cartridge-java/issues/77

Close old connections when address provider returns new addresses

---

pom.xml
src/main/java/io/tarantool/driver/cluster/BinaryDiscoveryClusterAddressProvider.java
src/main/java/io/tarantool/driver/codecs/MessagePackFrameEncoder.java
src/main/java/io/tarantool/driver/core/RequestFutureManager.java
src/main/java/io/tarantool/driver/core/RetryingTarantoolClient.java
src/main/java/io/tarantool/driver/core/TarantoolChannelInitializer.java
src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionFactory.java
src/main/java/io/tarantool/driver/core/space/RetryingTarantoolSpace.java
src/main/java/io/tarantool/driver/handlers/TarantoolRequestHandler.java
src/test/java/io/tarantool/driver/api/conditions/ConditionsTest.java
src/test/java/io/tarantool/driver/integration/CartridgeMixedInstancesContainer.java
src/test/java/io/tarantool/driver/integration/ClientFactoryIT.java
src/test/java/io/tarantool/driver/integration/ClusterConnectionIT.java
src/test/java/io/tarantool/driver/integration/ClusterDiscoveryIT.java
src/test/java/io/tarantool/driver/integration/ClusterTarantoolTupleClientIT.java
src/test/java/io/tarantool/driver/integration/ClusterTruncateIT.java
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientMixedInstancesIT.java
src/test/java/io/tarantool/driver/integration/ReconnectIT.java
src/test/java/io/tarantool/driver/integration/RetryingTarantoolTupleClientIT.java
src/test/resources/cartridge/app/roles/api_router.lua
src/test/resources/cartridge/init.lua
src/test/resources/cartridge/instances_mixed.yml
src/test/resources/cartridge/replicasets.yml
src/test/resources/cartridge/topology.lua
src/test/resources/cartridge/topology_mixed.lua

Corrects topologies in tests. And added tests fixes.

Fix tests and warnings

---

src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
src/test/java/io/tarantool/driver/integration/ClientFactoryIT.java

Closes https://github.com/tarantool/cartridge-java/issues/184

Fix NPE in exception check predicate

---

pom.xml
src/main/java/io/tarantool/driver/api/tuple/TarantoolNullField.java
src/test/java/io/tarantool/driver/api/tuple/TarantoolNullFieldTest.java

Use super.hashCode instead of Objects.hashCode
Fix formatting in pom.xml
Closes https://github.com/tarantool/cartridge-java/issues/186

 Fix recursion in TarantoolNullField.hashCode method

---

src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
src/test/java/io/tarantool/driver/integration/ConnectionIT.java

Return empty list instead of NPE in AbstractTarantoolConnectionManager.getConnections
Closes #87

Fix NPE in AbstractTarantoolConnectionManager

---

src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapper.java
src/main/java/io/tarantool/driver/mappers/MessagePackObjectMapper.java
src/test/java/io/tarantool/driver/benchmark/BenchmarkRunner.java
src/test/java/io/tarantool/driver/benchmark/TarantoolSetup.java
src/test/resources/org/testcontainers/containers/benchmark.lua

* Added perf tests for objectConverters 
* Added cached object converters `ArrayList -> ArrayValue`, `HashMap -> MapValue`
Closes #207

Add objects converters for ArrayList and HashMap

---

.github/workflows/perf.yml
.github/workflows/tests.yml
CHANGELOG.md
pom.xml
src/test/java/io/tarantool/driver/benchmark/BenchmarkRunner.java
src/test/java/io/tarantool/driver/benchmark/TarantoolSetup.java

Now we can run these tests on a trigger in UI or via github rest.
Fixed unstoppable BenchmarkRunner.
Also added a manuall trigger in the default workflow.
You can see the result here https://github.com/tarantool/cartridge-java/actions/runs/2280786760

Add workflow for performance tests in CI

---

CHANGELOG.md
README.md
pom.xml
src/main/java/io/tarantool/driver/api/MessagePackMapperBuilder.java
src/main/java/io/tarantool/driver/api/TarantoolClientBuilder.java
src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
src/main/java/io/tarantool/driver/api/TarantoolServerAddress.java
src/main/java/io/tarantool/driver/cluster/HTTPClusterDiscoveryEndpoint.java
src/main/java/io/tarantool/driver/mappers/ConverterWrapper.java
src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java

Prepare for release 0.8.0

---

pom.xml

It's needed to check codestyle in ci.
Closes #197

Add fail on error/warning in checkstyle

---

src/test/java/io/tarantool/driver/TarantoolUtils.java
src/test/java/io/tarantool/driver/integration/ConvertersWithClusterClientIT.java
src/test/java/io/tarantool/driver/integration/ConvertersWithProxyClientIT.java
src/test/java/io/tarantool/driver/integration/SharedTarantoolContainer.java
src/test/resources/cartridge/app/roles/api_storage.lua
src/test/resources/org/testcontainers/containers/server.lua

Tests to verify correct work of converter `java UUID <-> tarantool uuid`

Add uuid tests

---

README.md

Add Tarantool logo

---

.gitignore
src/main/java/io/tarantool/driver/core/TarantoolRequestMetadata.java
src/main/java/io/tarantool/driver/core/connection/TarantoolConnectionFactory.java
src/main/java/io/tarantool/driver/protocol/TarantoolHeader.java
src/main/java/io/tarantool/driver/protocol/TarantoolRequestType.java
src/main/java/io/tarantool/driver/protocol/TarantoolResponseType.java

Add constants to align code more with documentation and for further refactoring

Add additional constants

---

.github/workflows/tests-ce.yml
.github/workflows/tests-ee.yml

Move tests with Tarantool Enterprise Edition into separate CI workflow.
Closes #239

Split tests workflows

---

CHANGELOG.md
README.md

Prepare for release 0.8.1

---

pom.xml

Rename repository name in pom.xml to actual

---

CHANGELOG.md
README.md
src/main/java/io/tarantool/driver/api/TarantoolClientBuilder.java
src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
src/main/java/io/tarantool/driver/core/AbstractTarantoolClient.java
src/main/java/io/tarantool/driver/core/TarantoolClientBuilderImpl.java
src/test/java/io/tarantool/driver/core/TarantoolClientBuilderTest.java

Add an option for specifying the number of Netty threads

---

CHANGELOG.md
src/main/java/io/tarantool/driver/core/proxy/AbstractProxyOperation.java
src/main/java/io/tarantool/driver/core/proxy/DeleteProxyOperation.java
src/main/java/io/tarantool/driver/core/proxy/InsertProxyOperation.java
src/main/java/io/tarantool/driver/core/proxy/ReplaceProxyOperation.java
src/main/java/io/tarantool/driver/core/proxy/SelectProxyOperation.java
src/main/java/io/tarantool/driver/core/proxy/TruncateProxyOperation.java
src/main/java/io/tarantool/driver/core/proxy/UpdateProxyOperation.java
src/main/java/io/tarantool/driver/core/proxy/UpsertProxyOperation.java

Remove repetitive code in ProxyOperationsBuilders

---

CHANGELOG.md
README.md

Prepare for release 0.8.2

---

CHANGELOG.md
README.md
src/main/java/io/tarantool/driver/api/TarantoolClientConfig.java
src/main/java/io/tarantool/driver/api/space/options/Options.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyDeleteOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyInsertManyOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyInsertOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyReplaceManyOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyReplaceOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxySelectOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyTruncateOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyUpdateOptions.java
src/main/java/io/tarantool/driver/api/space/options/proxy/ProxyUpsertOptions.java

Prepare for release 0.9.0

---

CHANGELOG.md
pom.xml

Netty version bump

---

CHANGELOG.md
pom.xml

Bump jackson version to 2.14.1-rc1

---

CHANGELOG.md
README.md

Prepare for release 0.9.1

---

CHANGELOG.md
src/main/java/io/tarantool/driver/mappers/DefaultMessagePackMapperFactory.java
src/main/java/io/tarantool/driver/mappers/converters/object/DefaultLongArrayToArrayValueConverter.java
src/main/java/io/tarantool/driver/mappers/converters/value/DefaultArrayValueToLongArrayConverter.java
src/test/java/io/tarantool/driver/mappers/DefaultLongArrayConverterTest.java
src/test/java/io/tarantool/driver/mappers/DefaultMessagePackMapperTest.java

long array mapper

---

.github/pull_request_template.md

Add commit section in pull request template

---

.github/ISSUE_TEMPLATE/task.md

I added a template for one reason. I don't like to add the project link every time I create an issue

Add issue template

---

CHANGELOG.md
README.md
pom.xml
src/test/java/io/tarantool/driver/TarantoolUtils.java
src/test/java/io/tarantool/driver/integration/ConvertersWithClusterClientIT.java
src/test/java/io/tarantool/driver/integration/ConvertersWithProxyClientIT.java
src/test/java/io/tarantool/driver/mappers/DefaultCharacterConverterTest.java
src/test/resources/junit-platform.properties

Fix debendency conflicts

---

README.md
src/test/java/io/tarantool/driver/integration/SingleInstanceExampleTest.java
src/test/resources/single-instance.lua

Updated quickstart section im readme according to your new documentation policy
Closes #305

Update quickstart in readme

---

src/test/java/io/tarantool/driver/integration/SingleInstanceExampleIT.java
src/test/resources/single-instance.lua

Fix example test name and codestyle

---

CHANGELOG.md
pom.xml

Use netty part dependencies instead of netty-all

---

CHANGELOG.md
pom.xml

It doesn't work without this dependency https://github.com/tarantool/cartridge-java/actions/runs/3698551253/jobs/6264898632

Return jmh-generator-annprocess

---

CHANGELOG.md
README.md

Prepare for release 0.10.1

---

src/main/java/io/tarantool/driver/api/retry/RequestRetryPolicy.java
src/main/java/io/tarantool/driver/api/retry/TarantoolRequestRetryPolicies.java
src/test/java/io/tarantool/driver/api/retry/RequestRetryPolicyTest.java

Refactor tests and code in retrying

---

README.md
docs/ProxyTarantoolClient.md
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientExampleIT.java

Update ProxyTarantoolClient documentation according to our new documentation policy
Closes #307

Update ProxyTarantoolClient documentation

---

README.md
docs/MultiInstanceConnecting.md
docs/ProxyTarantoolClient.md
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientWithAddressProviderExampleIT.java
src/test/java/io/tarantool/driver/integration/ReconnectIT.java
src/test/resources/cartridge/app/roles/custom.lua

Add Proxy Tarantool client example with multiple routers
Closes #348
Closes #349

Add Proxy Tarantool client example with multiple routers

---

README.md
docs/CustomShardingFunction.md

Update Custom sharding function documentation according to our new documentation policy
Closes #308

Update Custom sharding function documentation

---

README.md
docs/SslAndMtls.md
src/test/resources/org/testcontainers/containers/enterprise/ssl/gen.sh

Add documentation of SSL and mTLS usage with tarantool
Closes #353

Add examples of SSL and mTLS usage

---

README.md
docs/SpaceNotFound.md

Added page about solving space not found problem
Closes #142

Added space not found documentation

---

README.md
docs/MappersAndConverters.md

Add page about converters, mappers and mapper factories
Closes #205

Add mappers doc

---

src/test/java/io/tarantool/driver/integration/CartridgeMixedInstancesContainer.java
src/test/java/io/tarantool/driver/integration/SharedCartridgeContainer.java

Remove unnecessary build args from MixedContainer

---

CHANGELOG.md
src/main/java/io/tarantool/driver/cluster/AbstractDiscoveryClusterAddressProvider.java
src/main/java/io/tarantool/driver/core/connection/AbstractTarantoolConnectionManager.java
src/main/java/io/tarantool/driver/core/connection/TarantoolClusterConnectionManager.java
src/test/java/io/tarantool/driver/integration/ProxyTarantoolClientIT.java

Closes https://github.com/tarantool/cartridge-java/issues/404

Fix losing connection if restart happened faster than discovery task

---

CHANGELOG.md
README.md
src/main/java/io/tarantool/driver/api/retry/RequestRetryPolicy.java

Prepare for release 0.12.1

---

CHANGELOG.md
pom.xml

Bump netty version to 4.1.104.Final

---

src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java

Add example for FIRST crud operations option

---

src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/OperationWithForceMapCallOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/enums/ProxyOption.java
src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java

Add support for "force_map_call" option

---

src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/OperationWithFullScanOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/enums/ProxyOption.java
src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java

Add support for "fullscan" option

---

src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/OperationWithPreferReplicaOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/enums/ProxyOption.java
src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java

Add support for "prefer_replica" option

---

src/main/java/io/tarantool/driver/api/space/options/SelectOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/OperationWithBalanceOptions.java
src/main/java/io/tarantool/driver/api/space/options/crud/enums/ProxyOption.java
src/test/java/io/tarantool/driver/integration/proxy/options/ProxySpaceSelectOptionsIT.java

Add support for "balance" option
